/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.g16205.kovylina.task1;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream;

import lombok.Data;

@Data
public class App {
    private static final Logger LOGGER = LogManager.getLogger(App.class.getName());

    public static void main(String[] args) {
        if (args.length < 1) {
            throw new IllegalArgumentException("You should provide path to the file you want to process");
        }

        FileInputStream fileInputStream = new FileInputStream(args[0]);
        LOGGER.info("Stared processing XML file...");

        try {
            InputStream inputStream = new BZip2CompressorInputStream(fileInputStream)
            OsmParser osmParser = new OsmParser(inputStream);

            osmParser.process();
            osmParser.printResults();
        } catch (XMLStreamException exception) {
            LOGGER.error("Error occured while processing file", exception);
        } catch (FileNotFoundException exception) {
            LOGGER.error("Provided wrong path to the file", exception);
        }
    }
}
